# Generated by Django 4.0.6 on 2022-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.IntegerField()),
                ('deadwood', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='tanggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(null=True)),
                ('date2', models.DateField(null=True)),
            ],
        ),
    ]
